/**
 * InternalApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIItem.h"

namespace OpenAPI
{

/*
 * OpenAPIPlayer
 *
 * 
 */
class OPENAPI_API OpenAPIPlayer : public Model
{
public:
    virtual ~OpenAPIPlayer() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Id;
	TOptional<FString> Name;
	FString Email;
	FString Password;
	TOptional<TArray<OpenAPIItem>> Items;
};

}
