/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPlayer.h"

namespace OpenAPI
{
	class OpenAPIPlayer;

	/*
 * OpenAPIItem
 *
 * 
 */
class OPENAPI_API OpenAPIItem : public Model
{
public:
    virtual ~OpenAPIItem() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<int32> Id;
	TOptional<FString> Name;
	TOptional<TArray<OpenAPIPlayer>> Players;
};

}
