/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIPlayer.h"

namespace OpenAPI
{

/*
 * OpenAPIUserTokenViewModel
 *
 * 
 */
class OPENAPI_API OpenAPIUserTokenViewModel : public Model
{
public:
    virtual ~OpenAPIUserTokenViewModel() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<OpenAPIPlayer> User;
	TOptional<FString> AccessToken;
};

}
