/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIInternalApiApi.h"


namespace OpenAPI
{

/* 

*/
class APICLIENT_API OpenAPIInternalApiApi::ObjectRecoltedPostRequest : public Request
{
public:
    virtual ~ObjectRecoltedPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class APICLIENT_API OpenAPIInternalApiApi::ObjectRecoltedPostResponse : public Response
{
public:
    virtual ~ObjectRecoltedPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    bool Content;
};

}
