/**
 * Internal API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIAuthenticationApi.h"

#include "OpenAPIUserTokenViewModel.h"
#include "OpenAPIUserViewModel.h"

namespace OpenAPI
{

/* 

*/
class APICLIENT_API OpenAPIAuthenticationApi::AuthenticatePostRequest : public Request
{
public:
    virtual ~AuthenticatePostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIUserViewModel OpenAPIUserViewModel;
};

class APICLIENT_API OpenAPIAuthenticationApi::AuthenticatePostResponse : public Response
{
public:
    virtual ~AuthenticatePostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIUserTokenViewModel Content;
};

/* 

*/
class APICLIENT_API OpenAPIAuthenticationApi::RegisterUserPostRequest : public Request
{
public:
    virtual ~RegisterUserPostRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIUserViewModel OpenAPIUserViewModel;
};

class APICLIENT_API OpenAPIAuthenticationApi::RegisterUserPostResponse : public Response
{
public:
    virtual ~RegisterUserPostResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    FString Content;
};

}
