/**
 * InternalApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "../Public/OpenAPIUserTokenViewModel.h"

#include "OpenAPIModule.h"
#include "../Public/OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPIUserTokenViewModel::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (User.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("user")); WriteJsonValue(Writer, User.GetValue());
	}
	if (AccessToken.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("accessToken")); WriteJsonValue(Writer, AccessToken.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIUserTokenViewModel::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("user"), User);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("accessToken"), AccessToken);

	return ParseSuccess;
}

}
